USE master
GO
IF EXISTS (SELECT NAME FROM SYS.databases WHERE NAME LIKE 'TEST_822')
	DROP DATABASE TEST_822
GO

CREATE DATABASE TEST_822
GO

USE TEST_822
GO

CREATE TABLE BOOKS(
	ID INT PRIMARY KEY,
	TITLU VARCHAR(30),
);
GO

CREATE TABLE AUTHORS(
	
	ID SMALLINT, --IDENTITY(1,1)
	FIRST_NAME VARCHAR(30),
	SURENAME VARCHAR(30),
	PRIMARY KEY(ID)

);
GO

CREATE TABLE BOOKS_AUTHORS(
	ID_BOOK INT FOREIGN KEY REFERENCES BOOKS(ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
	ID_AUTHOR SMALLINT FOREIGN KEY REFERENCES AUTHORS(ID),
	PRIMARY KEY(ID_BOOK, ID_AUTHOR)
);
GO

CREATE TABLE PHONES(
	ID INT PRIMARY KEY,
	PHONE_NO CHAR(14),
	ID_AUTHOR SMALLINT FOREIGN KEY REFERENCES AUTHORS(ID) ON UPDATE CASCADE ON DELETE CASCADE
)

--DROP TABLE CARTI